travis:
  secure:
    BINSTAR_TOKEN: ABVmANwi7gJGoKNaI2P0T7DYXv1N9GP1wjp67LTAZ5zr6Su6oICx6Sw/2XvKYqoPoEgnkWSeo7wkeSDwYxqV13l9wrmSmd0aeE7KaRMDraY8MepbzMgwv7THDbUFYsSVyjpITBJlPzAyXSEIG+IeIDyJRZ4EVFZU2KoglzYMz4sRtynFeDBFKzfGH3V8POgkPhgref9oMPXeBAuhQ42WJ0zAtq9Qnm3uWzYFtEsYgfBtcHjdBNH4V/4olII0xME9BmX7inAJSe/c9a5NaQHd5xBs2ANmOscSZF9zjEgH7VPSmBfHyvy5nGHkl/dn/Y65iqf1QQm0unqp+XZrosISFN1U4f4NhanV3eacA97TuAk9yYz7UQYyaggeUbDRh9Lz55DINT/WcHxt0zE1so8mo3oyX1dQm7W2u3SoTULHMNEoPp8eWPu5o7/gJhN1CPWuMRabL1LFpO8wnU78sUnirM3/BpIS++DBcjHqSst/ADtKZfR0tjV8ZQZbtLAvIiNYd4BXbO1lIKtipU50gCwVkpIsQHr+PYlsPkklw/kuEjThik1UUfZaGAWKjlCNAbHdKVo76SvOHMRV1HZhZC2O3MsDhAIVzOl9UqYAhE+KwxXhXeV3IIKbyRe9rnZS4fDTKGTORHNX0ul03SjDAPRZMpR1vavPTPmTulvvbD1pCRo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
